In [1]:
# can you see my screen
# even number print 27-126
    

In [4]:
num = list(range(27,127,1))
print(num,end='')

[27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126]

In [5]:
for num in num:
    if num%2 == 0:
        print(num,end=' ')

28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 102 104 106 108 110 112 114 116 118 120 122 124 126 

In [42]:
import random
import numpy as np
raw_data = np.random.randint(2,10,size=(1,7))

In [43]:
raw_data

array([[9, 4, 2, 6, 6, 4, 7]])

In [44]:
raw_data.shape

(1, 7)

In [45]:
raw_data.sort()

In [46]:
print(raw_data)

[[2 4 4 6 6 7 9]]


In [47]:
raw_data

array([[2, 4, 4, 6, 6, 7, 9]])

In [54]:
import numpy as np
# Generate some example data
data = np.array([10, 12, 15, 18, 20])
# Calculate population variance
population_variance = np.var(data)
print(f"Population Variance: {population_variance}")

# Calculate population standard deviation
population_std_dev = np.std(data)
print(f"Population Standard Deviation: {population_std_dev}")

# Calculate sample variance (ddof=1 for sample variance)
sample_variance = np.var(data, ddof=1)
# ddof parameter in the np.var function stands for "Delta Degrees of Freedom."
# It represents the divisor used in the calculation of the variance and adjusts
# it for the sample size. When calculating the variance for a sample, 
# you typically divide by n - ddof, where n is the number of data points. Setting ddof to 1 

print(f"Sample Variance: {sample_variance}")

# Calculate sample standard deviation
sample_std_dev = np.std(data, ddof=1)
print(f"Sample Standard Deviation: {sample_std_dev}")


Population Variance: 13.6
Population Standard Deviation: 3.687817782917155
Sample Variance: 17.0
Sample Standard Deviation: 4.123105625617661


In [56]:
X=10
X=X+10
X=X-5

In [57]:
X

15

In [58]:
x, y = 20, 60  
y, x, y-x, y-10, x+10  
print (x, y)

20 60


In [13]:
n= 7
for i in range(n):
    for j in range(n):
#         print("*",end=' ')
        if j == i or i+j ==n-1:
            print("*",end=' ')

#             break;
    print()        
    

* * 
* * 
* * 
* 
* * 
* * 
* * 
